all:
  vars:
    ansible_user: root
  children:
    gpu_nodes:
      hosts:
        h200-node-1:
          ansible_host: 213.181.104.150
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.12
          storage_ip: 10.3.1.12
          node_id: 1
        h200-node-2:
          ansible_host: 213.181.104.151
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.13
          storage_ip: 10.3.1.13
          node_id: 2
        h200-node-3:
          ansible_host: 213.181.104.152
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.14
          storage_ip: 10.3.1.14
          node_id: 3
        h200-node-4:
          ansible_host: 213.181.104.157
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.17
          storage_ip: 10.3.1.17
          node_id: 4
        h200-node-5:
          ansible_host: 213.181.104.158
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.18
          storage_ip: 10.3.1.18
          node_id: 5
        h200-node-6:
          ansible_host: 213.181.104.162
          vm_ip: 192.168.100.2
          gpu_passthrough: true
          fabric: true
          intranet_ip: 10.2.1.26
          storage_ip: 10.3.1.26
          node_id: 6
